<a href="https://colab.research.google.com/github/EHISAMGOLD/Volunteers-Data/blob/master/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Data Structures

**Series**

In [ ]:
import pandas as pd

# Creating a Series from a list
data = [10, 20, 30, 40, 50]
series = pd.Series(data)

print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

**Dataframe**

In [ ]:

# Creating a DataFrame from a dictionary
data2 = {'Name': ['John', 'Jane', 'Mike'],
        'Age': [25, 30, 35],
        'City': ['New York', 'London', 'Paris']}
df = pd.DataFrame(data)

print(df)

    0
0  10
1  20
2  30
3  40
4  50

**Customizing index**

In [ ]:
# Creating a Series with custom index labels
data = [10, 20, 30, 40, 50]
index_labels = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index_labels)

print(series)

a    10
b    20
c    30
d    40
e    50
dtype: int64

## Data Analysis

**Data loading**

In [ ]:

# Load data from a CSV file
df = pd.read_csv('data.csv')

# Load data from an Excel file
df = pd.read_excel('data.xlsx')

# Load data from a SQL database
import sqlite3
connexion = sqlite3.connect('database.db')
query = "SELECT * FROM table_name"
df = pd.read_sql(query, connexion)

FileNotFoundError: ignored

**Data understanding**

In [ ]:
# Creating sample dataset
data = {
    'fruits': ['Apple', 'Banana', 'Orange', 'Cherry', 'Mango'],
    'ripe': [True, False, True, True, False],
    'weight': [1.3, 2.2, 3.2, 1.1, 2.1],
    'stock': [120, 320, 460, 240, 750],
    'date': ["July 3, 2023", "July 4, 2022", "July 6, 2021", "July 7, 2000", "July 10, 2010"]
}

# Creating DataFrame
df = pd.DataFrame(data)

In [ ]:
df.head()

   fruits   ripe  weight  stock           date
0   Apple   True     1.3    120   July 3, 2023
1  Banana  False     2.2    320   July 4, 2022
2  Orange   True     3.2    460   July 6, 2021
3  Cherry   True     1.1    240   July 7, 2000
4   Mango  False     2.1    750  July 10, 2010

In [ ]:
df.head()
df.tail()
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   fruits  5 non-null      object
 1   ripe    5 non-null      bool
 2   weight  5 non-null      float64
 3   stock   5 non-null      int64
 4   date    5 non-null      object
dtypes: bool(1), float64(1), int64(1), object(2)
memory usage: 293.0+ bytes

In [ ]:
# Descriptive Statistics
# Compute basic statistics of a column
mean_value = df['weight'].mean()
median_value = df['weight'].median()
std_value = df['weight'].std()

print(mean_value)
print(median_value)
print(std_value)

1.98
2.1
0.8348652585896722

In [ ]:
# Time Series Analysis
# Set a column as the index with datetime values
df['date'] = pd.to_datetime(df['date'])
df.set_index('date', inplace=False)
# df.set_index('date', inplace=True)

df.head()

   fruits   ripe  weight  stock       date
0   Apple   True     1.3    120 2023-07-03
1  Banana  False     2.2    320 2022-07-04
2  Orange   True     3.2    460 2021-07-06
3  Cherry   True     1.1    240 2000-07-07
4   Mango  False     2.1    750 2010-07-10

**Data Manipulation**

In [ ]:
# Selecting and Filtering Data
# Select rows where a condition is met
filtered_df = df[df['weight'] > 20]

# Select specific columns
selected_columns = ['weight', 'fruits']
df_selected = df[selected_columns]

# Selecting rows based on multiple conditions
filtered_data = df[(df['weight'] > 2) & (df['ripe'] == True)]

print(filtered_df)
print("========")
print(df_selected)
print("========")
print(filtered_data)

Empty DataFrame
Columns: [fruits, ripe, weight, stock, date]
Index: []
========
   weight  fruits
0     1.3   Apple
1     2.2  Banana
2     3.2  Orange
3     1.1  Cherry
4     2.1   Mango
========
   fruits  ripe  weight  stock       date
2  Orange  True     3.2    460 2021-07-06

In [ ]:
df.head()

   fruits   ripe  weight  stock       date
0   Apple   True     1.3    120 2023-07-03
1  Banana  False     2.2    320 2022-07-04
2  Orange   True     3.2    460 2021-07-06
3  Cherry   True     1.1    240 2000-07-07
4   Mango  False     2.1    750 2010-07-10

In [ ]:
# select a row based in its index
df.iloc[2]

fruits                 Orange
ripe                     True
weight                    3.2
stock                     460
date      2021-07-06 00:00:00
Name: 2, dtype: object

In [ ]:
df.set_index('fruits', inplace=True)
df.head()

         ripe  weight  stock       date
fruits
Apple    True     1.3    120 2023-07-03
Banana  False     2.2    320 2022-07-04
Orange   True     3.2    460 2021-07-06
Cherry   True     1.1    240 2000-07-07
Mango   False     2.1    750 2010-07-10

In [ ]:
# select a row based in its label name
df.loc[2]

ripe                     True
weight                    3.2
stock                     460
date      2021-07-06 00:00:00
Name: Orange, dtype: object

In [ ]:
# Drop rows with missing values
# df_cleaned = df.dropna()

# Fill missing values with a specific value
# df_filled = df.fillna(0)

print(df.isna())
print(df.isnull())

         ripe  weight  stock   date
fruits
Apple   False   False  False  False
Banana  False   False  False  False
Orange  False   False  False  False
Cherry  False   False  False  False
Mango   False   False  False  False
         ripe  weight  stock   date
fruits
Apple   False   False  False  False
Banana  False   False  False  False
Orange  False   False  False  False
Cherry  False   False  False  False
Mango   False   False  False  False

In [ ]:
# Data Transformation
# Sort data by a column
df_sorted = df.sort_values('weight')

# Sorting data based on multiple columns
sorted_data = df.sort_values(['weight', 'fruits'])

# Replacing values in a column
# df['column'].replace('old_value', 'new_value', inplace=True)

# Filling missing values with a specific value
# df['column'].fillna('value', inplace=True)

print(df_sorted)
print("==========")
print(sorted_data)

         ripe  weight  stock       date
fruits
Cherry   True     1.1    240 2000-07-07
Apple    True     1.3    120 2023-07-03
Mango   False     2.1    750 2010-07-10
Banana  False     2.2    320 2022-07-04
Orange   True     3.2    460 2021-07-06
==========
         ripe  weight  stock       date
fruits
Cherry   True     1.1    240 2000-07-07
Apple    True     1.3    120 2023-07-03
Mango   False     2.1    750 2010-07-10
Banana  False     2.2    320 2022-07-04
Orange   True     3.2    460 2021-07-06

In [ ]:
# Grouping data and calculating the mean
grouped_data = df.groupby('weight').mean()

# Group data by a column and compute the mean of another column
grouped_data2 = df.groupby('weight')['stock'].mean()

print(grouped_data)
print("==========")
print(grouped_data2)

        ripe  stock
weight
1.1      1.0  240.0
1.3      1.0  120.0
2.1      0.0  750.0
2.2      0.0  320.0
3.2      1.0  460.0
==========
weight
1.1    240.0
1.3    120.0
2.1    750.0
2.2    320.0
3.2    460.0
Name: stock, dtype: float64

<ipython-input-134-aff36e1ae646>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped_data = df.groupby('weight').mean()

In [ ]:
# Apply a function to a column
df['weight_doubled'] = df['weight'].apply(lambda x: x*2)

In [ ]:
df.head()

         ripe  weight  stock       date  weight_doubled
fruits
Apple    True     1.3    120 2023-07-03             2.6
Banana  False     2.2    320 2022-07-04             4.4
Orange   True     3.2    460 2021-07-06             6.4
Cherry   True     1.1    240 2000-07-07             2.2
Mango   False     2.1    750 2010-07-10             4.2

**Advanced Topics**

In [ ]:

# Grouping data by multiple columns and calculating multiple aggregate functions
grouped_data = df.groupby(['column1', 'column2']).agg({'column3': 'sum', 'column4': 'mean'})

# Applying different aggregate functions to different columns
grouped_data = df.groupby('column').agg({'column1': 'sum', 'column2': 'mean'})

# Merging two DataFrames based on a common column
merged_data = pd.merge(df1, df2, on='common_column')

# Joining two DataFrames based on the index
joined_data = df1.join(df2, lsuffix='_left', rsuffix='_right')

# Mapping values to a new column
mapping = {'value1': 1, 'value2': 2, 'value3': 3}
df['new_column'] = df['column'].map(mapping)

In [ ]:
import pandas as pd
import pandas_profiling

# Load data into a DataFrame
df = pd.read_csv('data.csv')

# Generate a profile report
profile = df.profile_report()

# Save the report as an HTML file
profile.to_file("report.html")

**Export**

In [ ]:
# Export data to a CSV file
df.to_csv('output.csv', index=False)

# Export data to an Excel file
df.to_excel('output.xlsx', index=False)

# Save data to a SQL database
df.to_sql('new_table_name', connexion, if_exists='replace')